services:
  app:
    container_name: login-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001" # host:container mapping for Laravel
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    command: sh -c "composer install && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8001"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3307
      DB_DATABASE: traning
      DB_USERNAME: root
      DB_PASSWORD: "#6073shaH"

  node:
    image: node:20
    container_name: laravel_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "5174:5174" # host:container mapping for Vite or npm run dev
    command: sh -c "npm install"

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_DATABASE: traning
      MYSQL_ROOT_PASSWORD: "#6073shaH"
    ports:
      - "3307:3307"
    command: --port=3307
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: